lowercaseOutputName: true
lowercaseOutputLabelNames: true
rules:
  - pattern: kafka.(\w+)<type=(.+), name=(.+)><>Value
    name: kafka_$1_$2_$3
    type: GAUGE
  - pattern: kafka.(\w+)<type=(.+), name=(.+)><>Count
    name: kafka_$1_$2_$3_count
    type: COUNTER
  - pattern: kafka.(\w+)<type=(.+), name=(.+)><>(\d+)thPercentile
    name: kafka_$1_$2_$3
    type: GAUGE
    labels:
      quantile: "0.$4"
  - pattern: kafka.(\w+)<type=(.+), name=(.+)><>Mean
    name: kafka_$1_$2_$3_mean
    type: GAUGE
  - pattern: kafka.(\w+)<type=(.+), name=(.+)><>OneMinuteRate
    name: kafka_$1_$2_$3_one_minute_rate
    type: GAUGE
