global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Core infrastructure monitoring only
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'schema-registry'
    static_configs:
      - targets: ['schema-registry:7072']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:7071']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  # File-based service discovery for dynamic services
  - job_name: 'services'
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets/*.yml'
        refresh_interval: 5s
