apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: shared-resources
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/part-of: kmp-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kafka
        app.kubernetes.io/part-of: kmp-services
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.5.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: kafka
              containerPort: 9092
              protocol: TCP
            - name: internal
              containerPort: 29092
              protocol: TCP
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
            - name: KAFKA_LISTENERS
              value: "INSIDE://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INSIDE://kafka:29092,OUTSIDE://kafka:9092"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INSIDE"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_LOG4J_ROOT_LOGLEVEL
              value: "INFO"
            - name: KAFKA_TOOLS_LOG4J_LOGLEVEL
              value: "INFO"
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
          volumeMounts:
            - name: data
              mountPath: /var/lib/kafka/data
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
      volumes:
        - name: data
          emptyDir: {} 