apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: shared-resources
  labels:
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/part-of: kmp-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: zookeeper
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zookeeper
        app.kubernetes.io/part-of: kmp-services
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:7.5.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: client
              containerPort: 2181
              protocol: TCP
            - name: follower
              containerPort: 2888
              protocol: TCP
            - name: leader
              containerPort: 3888
              protocol: TCP
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
            - name: ZOOKEEPER_INIT_LIMIT
              value: "5"
            - name: ZOOKEEPER_SYNC_LIMIT
              value: "2"
            - name: ZOOKEEPER_MAX_CLIENT_CNXNS
              value: "60"
            - name: ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL
              value: "24"
            - name: ZOOKEEPER_AUTOPURGE_SNAP_RETAIN_COUNT
              value: "5"
            - name: ZOOKEEPER_4LW_COMMANDS_WHITELIST
              value: "*"
          volumeMounts:
            - name: data
              mountPath: /var/lib/zookeeper/data
            - name: log
              mountPath: /var/lib/zookeeper/log
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            tcpSocket:
              port: client
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: client
            initialDelaySeconds: 20
            periodSeconds: 10
      volumes:
        - name: data
          emptyDir: {}
        - name: log
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: shared-resources
  labels:
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/part-of: kmp-services
spec:
  type: ClusterIP
  ports:
    - port: 2181
      targetPort: client
      protocol: TCP
      name: client
    - port: 2888
      targetPort: follower
      protocol: TCP
      name: follower
    - port: 3888
      targetPort: leader
      protocol: TCP
      name: leader
  selector:
    app.kubernetes.io/name: zookeeper 