services:
  template-service:
    container_name: template-service
    build:
      context: ../.. # Root of the project for accessing common-libs
      dockerfile: examples/template-service/Dockerfile
    ports:
      - '8086:8086'
    environment:
      # Core infrastructure connections
      REGISTRY_URL: http://service-registry:8761
      CONFIG_SERVER_URL: http://config-server:8888
      SERVICE_URL: http://template-service:8086

      # Messaging configuration
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SCHEMA_REGISTRY_URL: http://schema-registry:8081

      # Monitoring
      MONITORING_ENABLED: 'true'

      # Service specific
      SERVICE_TYPE: producer
      PORT: 8086
      HOST: template-service
      APPLICATION_NAME: TEMPLATE-SERVICE
    networks:
      - core-network
      - app-network
      - monitoring-network

networks:
  core-network:
    name: kmp-core-network
    external: true
  app-network:
    name: kmp-app-network
    external: true
  monitoring-network:
    name: kmp-monitoring-network
    external: true
