apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ingress.yaml
  - kafka-config.yaml

commonLabels:
  app.kubernetes.io/part-of: kmp-services
  app.kubernetes.io/managed-by: kustomize
