apiVersion: v1
kind: Namespace
metadata:
  name: kmp-services
  labels:
    istio-injection: enabled
    monitoring: enabled
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: kmp-resource-quota
  namespace: kmp-services
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "20"
