apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kmp-services-prod

resources:
  - ../../base

commonLabels:
  environment: prod

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
  target:
    kind: Deployment
    name: service-a

images:
- name: kmp-service-a
  newName: ghcr.io/your-org/kmp-service-a
  newTag: prod
