apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  namespace: kmp-services
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - name: service-a
        image: kmp-service-a:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        env:
        - name: JAVA_OPTS
          value: "-Xms256m -Xmx512m"
        - name: SERVICE_NAME
          value: "service-a"
---
apiVersion: v1
kind: Service
metadata:
  name: service-a
  namespace: kmp-services
spec:
  selector:
    app: service-a
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP
