apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/deployment.yaml
  - resources/service.yaml
  - resources/monitoring.yaml

configurations:
  - variants.yaml

vars:
  - name: SERVICE_NAME
    objref:
      kind: ConfigMap
      name: service-config
      apiVersion: v1
  - name: SERVICE_PORT
    objref:
      kind: Service
      name: service
      apiVersion: v1
    fieldref: spec.ports[0].port

commonLabels:
  app.kubernetes.io/managed-by: kmp-infra
