apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "service-base.fullname" . }}-config
  labels:
    {{- include "service-base.labels" . | nindent 4 }}
data:
  application.conf: |
    ktor {
      deployment {
        port = {{ .Values.service.port }}
      }
      application {
        modules = [ com.example.kmp.ApplicationKt.module ]
      }
    }
    
    monitoring {
      enabled = {{ .Values.monitoring.enabled }}
      {{- if .Values.monitoring.enabled }}
      port = {{ .Values.monitoring.port }}
      {{- end }}
    }
    
    kafka {
      enabled = {{ .Values.kafka.enabled }}
      {{- if .Values.kafka.enabled }}
      bootstrap.servers = {{ .Values.kafka.bootstrapServers | quote }}
      {{- end }}
    }
    
    {{- range $key, $value := .Values.config }}
    {{ $key }} = {{ $value | quote }}
    {{- end }}
