apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "service-base.fullname" . }}
  labels:
    {{- include "service-base.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "service-base.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
        {{- if .Values.monitoring.enabled }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
        {{- end }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
        {{- if .Values.monitoring.enabled }}
        - protocol: TCP
          port: {{ .Values.monitoring.port }}
        {{- end }}
  egress:
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    {{- if .Values.kafka.enabled }}
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kafka
      ports:
        - protocol: TCP
          port: 9092
    {{- end }}
