apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kmp-services-dev

resources:
  - ../../base

commonLabels:
  environment: dev

patches:
- patch: |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: kafka-config
    data:
      bootstrap.servers: "kafka-dev.kmp-services-dev:9092"
      schema.registry.url: "http://schema-registry-dev.kmp-services-dev:8081"
      auto.register.schemas: "true"
      use.latest.version: "true"
      environment.name: "dev"

configMapGenerator:
- name: env-config
  behavior: create
  literals:
    - ENVIRONMENT=dev
    - LOG_LEVEL=DEBUG
    - MONITORING_ENABLED=true
    - TRACING_ENABLED=true
    - TRACING_SAMPLE_RATE=1.0
