apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kmp-services-dev

resources:
  - ../../base

commonLabels:
  environment: dev

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: service-b

images:
- name: kmp-service-b
  newName: ghcr.io/your-org/kmp-service-b
  newTag: dev
