apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: kmp-control-plane
spec:
  profile: default
  components:
    base:
      enabled: true
    pilot:
      enabled: true
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          service:
            type: LoadBalancer
    egressGateways:
      - name: istio-egressgateway
        enabled: true
  values:
    global:
      proxy:
        autoInject: enabled
    telemetry:
      enabled: true
      v2:
        enabled: true
        prometheus:
          enabled: true 