apiVersion: v1
kind: Service
metadata:
  name: weather-service
  namespace: default
  labels:
    app.kubernetes.io/name: weather-service
    app.kubernetes.io/part-of: kmp-services
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: weather-service 