apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
  namespace: kmp-services
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
      - name: service-b
        image: kmp-service-b:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8082
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 15
          periodSeconds: 20
        env:
        - name: JAVA_OPTS
          value: "-Xms256m -Xmx512m"
        - name: SERVICE_NAME
          value: "service-b"
---
apiVersion: v1
kind: Service
metadata:
  name: service-b
  namespace: kmp-services
spec:
  selector:
    app: service-b
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: ClusterIP
