apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kmp-services

resources:
  - deployment.yaml

commonLabels:
  app: service-b
  app.kubernetes.io/name: service-b
  app.kubernetes.io/part-of: kmp-services
