apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/mesh.yaml
  - monitoring/monitoring.yaml
  - gateway/gateway.yaml

commonLabels:
  app.kubernetes.io/part-of: kmp-shared-infra
  app.kubernetes.io/managed-by: kustomize

namespace: default 