apiVersion: v1
kind: Service
metadata:
  name: service-registry
  namespace: default
  labels:
    app.kubernetes.io/name: service-registry
    app.kubernetes.io/part-of: kmp-services
spec:
  type: ClusterIP
  ports:
    - port: 8761
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: service-registry 