global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'service-a'
    static_configs:
      - targets: ['service-a:8081']

  - job_name: 'service-b'
    static_configs:
      - targets: ['service-b:8082']
