apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kmp-services-prod

resources:
  - ../../base
  - network-policy.yaml

commonLabels:
  environment: prod

patches:
- patch: |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: kafka-config
    data:
      bootstrap.servers: "kafka-prod.kmp-services-prod:9092"
      schema.registry.url: "http://schema-registry-prod.kmp-services-prod:8081"
      auto.register.schemas: "false"
      use.latest.version: "false"
      environment.name: "prod"
- patch: |-
    apiVersion: v1
    kind: ResourceQuota
    metadata:
      name: kmp-resource-quota
    spec:
      hard:
        requests.cpu: "8"
        requests.memory: 16Gi
        limits.cpu: "16"
        limits.memory: 32Gi
        pods: "50"

configMapGenerator:
- name: env-config
  behavior: create
  literals:
    - ENVIRONMENT=prod
    - LOG_LEVEL=WARN
    - MONITORING_ENABLED=true
    - TRACING_ENABLED=true
    - TRACING_SAMPLE_RATE=0.1
    - RATE_LIMIT_RPS=500
    - CIRCUIT_BREAKER_THRESHOLD=0.2
    - CACHE_TTL=3600
    - RETRY_MAX_ATTEMPTS=3
    - RETRY_INITIAL_DELAY=1000

