#!/bin/bash

echo "Network Validation Instructions:"
echo ""
echo "1. Ensure shared infrastructure is running first:"
echo "   cd /Users/adamkumm/Documents/Development/kmp-shared-infra"
echo "   docker-compose up -d"
echo ""
echo "2. Start the weather service:"
echo "   cd examples/weather-service"
echo "   docker-compose up -d"
echo ""
echo "3. Validate network connectivity:"
echo "   a. View Kafka events at http://localhost:8080 (Kafka UI)"
echo "      - Look for the 'weather.update' topic"
echo "   b. View metrics at http://localhost:3000 (Grafana)"
echo "      - Default login: admin/admin"
echo "      - Look for weather_requests_total and weather_request_duration metrics"
echo ""
echo "4. Generate test events:"
echo "   curl http://localhost:8084/weather?city=London"
echo ""
echo "5. Check results:"
echo "   - Kafka UI should show new events in the weather.update topic"
echo "   - Grafana should show increased request counts and timing metrics"
