apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry
  namespace: kafka
  labels:
    app.kubernetes.io/name: schema-registry
    app.kubernetes.io/part-of: kmp-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: schema-registry
  template:
    metadata:
      labels:
        app.kubernetes.io/name: schema-registry
        app.kubernetes.io/part-of: kmp-services
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: schema-registry
          image: confluentinc/cp-schema-registry:7.5.1
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              echo "Starting Schema Registry with debug logging..."
              export SCHEMA_REGISTRY_LOG4J_LOGGERS="io.confluent=DEBUG,org.apache.kafka=DEBUG,org.apache.zookeeper=DEBUG"
              export SCHEMA_REGISTRY_DEBUG=true
              export SCHEMA_REGISTRY_TOOLS_LOG4J_LOGLEVEL=DEBUG
              echo "Environment variables:"
              env | sort
              echo "Starting Schema Registry..."
              /etc/confluent/docker/run
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: "schema-registry"
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: "kafka-cluster-kafka-bootstrap.kafka:9092"
            - name: SCHEMA_REGISTRY_LISTENERS
              value: "http://0.0.0.0:8081"
            - name: SCHEMA_REGISTRY_KAFKASTORE_TOPIC
              value: "_schemas"
            - name: SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL
              value: "PLAINTEXT"
            - name: SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL
              value: "DEBUG"
            - name: SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: SCHEMA_REGISTRY_KAFKASTORE_INIT_TIMEOUT_MS
              value: "60000"
            - name: SCHEMA_REGISTRY_KAFKASTORE_TIMEOUT_MS
              value: "60000"
            - name: SCHEMA_REGISTRY_DEBUG
              value: "true"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /subjects
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /subjects
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: schema-registry
  namespace: kafka
  labels:
    app.kubernetes.io/name: schema-registry
    app.kubernetes.io/part-of: kmp-services
spec:
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app.kubernetes.io/name: schema-registry 