apiVersion: v1
kind: Service
metadata:
  name: schema-registry
  namespace: shared-resources
  labels:
    app.kubernetes.io/name: schema-registry
    app.kubernetes.io/part-of: kmp-services
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: schema-registry 