apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kmp-services-staging

resources:
  - ../../base

commonLabels:
  environment: staging

patches:
- patch: |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: kafka-config
    data:
      bootstrap.servers: "kafka-staging.kmp-services-staging:9092"
      schema.registry.url: "http://schema-registry-staging.kmp-services-staging:8081"
      auto.register.schemas: "true"
      use.latest.version: "true"
      environment.name: "staging"

configMapGenerator:
- name: env-config
  behavior: create
  literals:
    - ENVIRONMENT=staging
    - LOG_LEVEL=INFO
    - MONITORING_ENABLED=true
    - TRACING_ENABLED=true
    - TRACING_SAMPLE_RATE=0.5
    - RATE_LIMIT_RPS=100
    - CIRCUIT_BREAKER_THRESHOLD=0.3
